"""anti_block.forms.hcaptcha_hsw — HSW token client for hCaptcha HSW variant.

hCaptcha occasionally returns a `rqdata` token when challenged. Standard
solvers (incl. korolossamy/hcaptcha-ai-solver) reject this — they need a
fresh HSW token generated by running the obfuscated `hsw.js` from hCaptcha
in a real JS context.

This module is a thin client to the local Flask service at port 5000
(`/home/deploy/hcaptcha-ai-solver/hsw_api.py`, managed by systemd unit
`hcaptcha-hsw.service`).

Flow from Hermes skill:
  1. Standard `anti_block.captcha.hcaptcha` returns error with rqdata.
  2. Skill calls this module: get_hsw_token(rqdata, host).
  3. Module POSTs to localhost:5000/hsw, returns the token string.
  4. Skill retries the standard solver with hsw= argument.

CLI:
    python3 -m anti_block.forms.hcaptcha_hsw --rqdata <JWT> --host baxterbet.com

Output (JSON):
    {"ok": true, "hsw_token": "...", "elapsed_s": 4.1}
    {"ok": false, "error": "service_unreachable" | "service_failed" | "timeout"}
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from typing import Optional

logger = logging.getLogger(__name__)

DEFAULT_ENDPOINT = "http://127.0.0.1:5000/hsw"


def get_hsw_token(rqdata: str, host: str, endpoint: str = DEFAULT_ENDPOINT, timeout: int = 30) -> dict:
    """Call local HSW service. Returns dict with ok/hsw_token/error."""
    try:
        import httpx
    except ImportError:
        return {"ok": False, "error": "httpx_missing"}

    t0 = time.time()
    try:
        r = httpx.post(endpoint, json={"req": rqdata, "host": host}, timeout=timeout)
    except httpx.ConnectError:
        return {"ok": False, "error": "service_unreachable", "elapsed_s": round(time.time() - t0, 2),
                "hint": "is hcaptcha-hsw systemd service running? `systemctl status hcaptcha-hsw`"}
    except httpx.TimeoutException:
        return {"ok": False, "error": "timeout", "elapsed_s": round(time.time() - t0, 2)}
    except Exception as e:
        return {"ok": False, "error": f"{type(e).__name__}: {str(e)[:200]}", "elapsed_s": round(time.time() - t0, 2)}

    if r.status_code != 200:
        return {"ok": False, "error": f"http_{r.status_code}", "body": (r.text or "")[:200], "elapsed_s": round(time.time() - t0, 2)}

    token = (r.text or "").strip()
    if not token or token == "None":
        return {"ok": False, "error": "service_failed", "body": token[:200], "elapsed_s": round(time.time() - t0, 2)}

    return {"ok": True, "hsw_token": token, "elapsed_s": round(time.time() - t0, 2)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rqdata", required=True, help="rqdata JWT from hCaptcha response")
    ap.add_argument("--host", required=True, help="target site hostname (matches hCaptcha challenge)")
    ap.add_argument("--endpoint", default=DEFAULT_ENDPOINT)
    ap.add_argument("--timeout", type=int, default=30)
    args = ap.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s", stream=sys.stderr)
    res = get_hsw_token(args.rqdata, args.host, endpoint=args.endpoint, timeout=args.timeout)
    print(json.dumps(res, ensure_ascii=False))
    return 0 if res.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
